### ISSUE TITLE
is-between does not work as intended for DAY values

### ISSUE THREAD

**Issue by SFRailsback** [NetLogo/Time-Extension#20]
time:is-between does not work as intended when its parameters are of type "DAY". This is probably because our original code did not work properly, but it is definitely a bug. The purpose of this primitive is to determine whether the current date is within some portion of the year defined by two DAY values: Is it legal to hunt deer today if the hunting season always starts on 11/1 and ends on 12/31? Or if the season starts on 11/1 and ends on 2/28 of the next year? This means that it must consider the case where logotime2 is greater than logotime3, so the portion of year of interest spans the end of the year. And we need to be clear about what happens if any of the 3 parameters are equal to each other. 

Here is my algorithm for is-between using DAY values: 
a) if logotime3 > logotime2, then report TRUE if logotime1 >= logotime2 and logotime1 <= logotime3, and FALSE otherwise.
b) if logotime3 < logotime2, then report FALSE if logotime1 > logotime2 and logotime1 < logotime3, and TRUE otherwise.
c) if logotime2 = logotime3, report TRUE. (See below.)

Here is draft documentation that describes what should happen:

When used with logotimes of type "DAY", is-between can be used to determine whether a time falls within some specific portion or season of the year. For example, if we want to know whether the current simation time (the logotime "sim-time" of type DATETIME) falls between 1 May and 30 June, we can use:
  let sim-day time:create (time:show sim-time "MM-dd")
  let is-in-May-June? time:is-between sim-day (time:create "05-01") (time:create "06-30")
This also works if the part of the year defined by logotime2 and logotime3 spans the end of the year--if logotime 2 is less than logotime 3. For example, if we want to know if sim-time is in winter, defined as December-February, we can use:
  let is-in-winter? time:is-between sim-day (time:create "12-01") (time:create "02-28")

If logotime1 is equal to either logotime2 or logotime3, is-between reports "TRUE". If logotime2 equals logotime3, is-between always reports "TRUE" (the season defined by logotime2 and logotime3 is assumed to include the whole year).

**Comment by charlesres** [comment]
Thanks @SFRailsback for reporting this issue. The algorithm mentioned above would work for the "DAY" type and would make handling the addition of leap days a bit simpler. I'll take a look at adding it in.
