### ISSUE TITLE
Document conventions and behavior for numbering hours, minutes, seconds

### ISSUE THREAD

**Issue by SFRailsback** [NetLogo/Time-Extension#23]
The documentation needs to describe the conventions used to hours, minutes, and seconds. I *think* they are that hours are 0-23, and minutes and seconds are 0-59. 

We also need to document what happens when input not following these conventions is used: will time:create etc. convert an hour of 24 into hour 0 of the next day?

(I'm willing to test how this stuff works.)

**Comment by charlesres** [comment]
@SFRailsback, thanks for the submission. I'll add some details about the bounds of each unit of time. This would help a lot with understanding its application. With documenting invalid input, would that be because some primitives support lenient parsing?
