### ISSUE TITLE
Error in results from ts-get-interp

### ISSUE THREAD

**Issue by SFRailsback** [NetLogo/Time-Extension#25]
time:ts-get-interp seems to calculate results correctly except they are formatted incorrectly. The primitive returns values such as "136.00.8333333333333334" when they should be "136.8333333333333334"

**Comment by jzkelter** [comment]
They also just seem to not interpolate correctly. In TimeSeriesExample.nlogo the "flow" value for "2000-01-01 00:00:00" is 1000 and the "flow' value for "2000-01-01 01:00:00" is 1010. So the interpolation at "2000-01-01 00:30:00" should be 1005, but it returns 1040. 
<img width="871" alt="Screen Shot 2020-05-06 at 10 50 29 AM" src="https://user-images.githubusercontent.com/4740759/81205067-68cf6280-8f87-11ea-83c1-6b6f96006000.png">

**Comment by jzkelter** [comment]
This is no longer included directly in the time-extension, but rather in NetLogo code in time-series.nls. Should be taken care of there.
