### ISSUE TITLE
time:ts-get does not always get the right value

### ISSUE THREAD

**Issue by SFRailsback** [NetLogo/Time-Extension#26]
ts-get is supposed to look for an exact date/time match in the logotimeseries object and if it doesn't find one, return the value with the closest date/time. This does not seem to be working consistently.

Here is an example when the logotimeseries contains one value per day, at 12 noon:
time:ts-get for 7/16/2010 23:00 returns the logotimeseries value associated with the time 7/17/2010 12:00 instead of 7/16/2010 12:00.

I suspect that the code is returning the next value in the logotimeseries after the input time instead of finding the nearest time.
--

**Comment by jzkelter** [comment]
This is no longer included directly in the time-extension, but rather in NetLogo code in time-series.nls. Should be taken care of there.
