### ISSUE TITLE
ts-get-range usually returns empty list

### ISSUE THREAD

**Issue by SFRailsback** [NetLogo/Time-Extension#27]
I tried a test code on time:ts-get-range and found that the primitive usually returns an empty list when it should not. One of many examples: I used a logotimeseries containing one value per day, at 12 noon. This range of dates: 2/1/2010 17:00 to 8/16/2012 15:00 produced an empty list.

(It is not clear that this ever worked in our original code)

**Comment by jzkelter** [comment]
I wasn't able to reproduce this bug.

**Comment by jzkelter** [comment]
This is no longer included directly in the time-extension, but rather in NetLogo code in time-series.nls. Should be taken care of there.
