### ISSUE TITLE
Documentation needs to say what time:ts-get-range does when logotime1 is after logotime2

### ISSUE THREAD

**Issue by SFRailsback** [NetLogo/Time-Extension#28]
Currently the documentation does not say what ts-get-range will do if logotime1 is after logotime2. I think it would be best if the primitive still returns a list of values in the logotimeseries between the two input logotimes, but with the order reversed. So  this statement:

time:ts-get-range logotimeseries logotime1 logotime2 column-name

returns the same list as:

time:ts-get-range logotimeseries logotime2 logotime1 column-name
except with the order of the list reversed.

**Comment by jzkelter** [comment]
This is included in the docs now.

**Comment by jzkelter** [comment]
As of now, the same list is returned either way. The user can reverse the order if they want.
