### ISSUE TITLE
ts-get-exact return false instead of throw an exception?

### ISSUE THREAD

**Issue by SFRailsback** [NetLogo/Time-Extension#33]
This is a primitive design suggestion. The original primitive:
time:ts-get-exact

does this:
Behaves almost identical to time:ts-get, but if there is not an exact match with the date/time stamp, then an exception is thrown.

It seems more the NetLogo way to have it return FALSE instead of throwing an exception if there is not an exact time match in the logotimeseries?

**Comment by jzkelter** [comment]
This is no longer included directly in the time-extension, but rather in NetLogo code in time-series.nls. Should be taken care of there.
