### ISSUE TITLE
time:show gives wrong year in late December

### ISSUE THREAD

**Issue by SFRailsback** [NetLogo/Time-Extension#43]
Sometimes time:show produces a year that is one year too high: when the Logotime value is 
{{time:logotime 2001-12-30 23:14:49297}}
time:show returns:
12/30/2002 23:14

This happens in late December. (I vaguely remember identifying this before??)

See attached demo file- click "run-demo-a-year" at least twice to see error.
[Demo-ShowError_2020-09-30.zip](https://github.com/NetLogo/Time-Extension/files/5307082/Demo-ShowError_2020-09-30.zip)

**Comment by jzkelter** [comment]
I don't think this is actually a bug, just a confusion with 'YYYY' vs 'yyyy'. The attached file uses 'YYYY' which is a week based year vs 'yyyy' which is a day based year. See the note at the end of https://github.com/NetLogo/Time-Extension#supported-format-characters
